"""Add credit_balance to Tenant and create ExecutionCost table

Revision ID: def456ghi789
Revises: abc123def456
Create Date: 2025-08-23 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'def456ghi789'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add credit_balance column to Tenant table
    op.add_column('tenant', sa.Column('credit_balance', sa.Float(), nullable=False, server_default='25.0'))
    
    # Create ExecutionCost table
    op.create_table('executioncost',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('step_name', sa.String(), nullable=False),
        sa.Column('model_used', sa.String(), nullable=False),
        sa.Column('input_tokens', sa.Integer(), nullable=False),
        sa.Column('output_tokens', sa.Integer(), nullable=False),
        sa.Column('step_cost', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add index for efficient querying
    op.create_index('ix_executioncost_tenant_id', 'executioncost', ['tenant_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index
    op.drop_index('ix_executioncost_tenant_id', table_name='executioncost')
    
    # Drop ExecutionCost table
    op.drop_table('executioncost')
    
    # Drop credit_balance column from Tenant table
    op.drop_column('tenant', 'credit_balance')
    
    # ### end Alembic commands ###