"""Add Job and ExecutionTraceStep models for async execution

Revision ID: 23f80bf3e6cd
Revises: ed067a43fe61
Create Date: 2025-08-31 11:03:20.321064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f80bf3e6cd'
down_revision: Union[str, Sequence[str], None] = 'ed067a43fe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executiontracestep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('step_type', sa.Enum('THOUGHT', 'ACTION', 'OBSERVATION', 'COST_UPDATE', name='steptype'), nullable=False),
    sa.Column('thought', sa.String(), nullable=True),
    sa.Column('action_tool', sa.String(), nullable=True),
    sa.Column('action_input', sa.String(), nullable=True),
    sa.Column('observation_result', sa.String(), nullable=True),
    sa.Column('step_cost', sa.Numeric(scale=6), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executiontracestep_job_id'), 'executiontracestep', ['job_id'], unique=False)
    op.create_index(op.f('ix_executiontracestep_step_number'), 'executiontracestep', ['step_number'], unique=False)
    op.create_index(op.f('ix_executiontracestep_step_type'), 'executiontracestep', ['step_type'], unique=False)
    op.create_index(op.f('ix_executiontracestep_tenant_id'), 'executiontracestep', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_executiontracestep_timestamp'), 'executiontracestep', ['timestamp'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PENDING_APPROVAL', name='jobstatus'), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('input_data', sa.String(), nullable=True),
    sa.Column('output_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('job_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_created_at'), 'job', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_job_id'), 'job', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_job_type'), 'job', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_tenant_id'), 'job', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    # NOTE: Removed destructive drop_table commands that were auto-generated incorrectly.
    # This migration should only ADD the Job and ExecutionTraceStep tables,
    # not drop existing core tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Only drop the tables we created in this migration
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_tenant_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_job_type'), table_name='job')
    op.drop_index(op.f('ix_job_job_id'), table_name='job')
    op.drop_index(op.f('ix_job_created_at'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_executiontracestep_timestamp'), table_name='executiontracestep')
    op.drop_index(op.f('ix_executiontracestep_tenant_id'), table_name='executiontracestep')
    op.drop_index(op.f('ix_executiontracestep_step_type'), table_name='executiontracestep')
    op.drop_index(op.f('ix_executiontracestep_step_number'), table_name='executiontracestep')
    op.drop_index(op.f('ix_executiontracestep_job_id'), table_name='executiontracestep')
    op.drop_table('executiontracestep')
