"""Add Tool, CustomAgentDefinition, AgentTeam models and expires_at to Job

Revision ID: 65c893f3540a
Revises: 23f80bf3e6cd
Create Date: 2025-08-31 18:27:30.199967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c893f3540a'
down_revision: Union[str, Sequence[str], None] = '23f80bf3e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentteam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_team_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('custom_agent_ids', sa.String(), nullable=False),
    sa.Column('pre_approved_tool_names', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_executions', sa.Integer(), nullable=True),
    sa.Column('default_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('team_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentteam_agent_team_id'), 'agentteam', ['agent_team_id'], unique=True)
    op.create_index(op.f('ix_agentteam_created_at'), 'agentteam', ['created_at'], unique=False)
    op.create_index(op.f('ix_agentteam_is_active'), 'agentteam', ['is_active'], unique=False)
    op.create_index(op.f('ix_agentteam_tenant_id'), 'agentteam', ['tenant_id'], unique=False)
    op.create_table('customagentdefinition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_agent_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('tool_names', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('custom_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customagentdefinition_created_at'), 'customagentdefinition', ['created_at'], unique=False)
    op.create_index(op.f('ix_customagentdefinition_custom_agent_id'), 'customagentdefinition', ['custom_agent_id'], unique=True)
    op.create_index(op.f('ix_customagentdefinition_is_active'), 'customagentdefinition', ['is_active'], unique=False)
    op.create_index(op.f('ix_customagentdefinition_tenant_id'), 'customagentdefinition', ['tenant_id'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('STABLE', 'BETA', 'DEPRECATED', name='toolstatus'), nullable=False),
    sa.Column('is_custom_agent_executor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('documentation_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_category'), 'tool', ['category'], unique=False)
    op.create_index(op.f('ix_tool_created_at'), 'tool', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=True)
    op.create_index(op.f('ix_tool_status'), 'tool', ['status'], unique=False)
    op.add_column('job', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_job_expires_at'), 'job', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_expires_at'), table_name='job')
    op.drop_column('job', 'expires_at')
    op.drop_index(op.f('ix_tool_status'), table_name='tool')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_created_at'), table_name='tool')
    op.drop_index(op.f('ix_tool_category'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_customagentdefinition_tenant_id'), table_name='customagentdefinition')
    op.drop_index(op.f('ix_customagentdefinition_is_active'), table_name='customagentdefinition')
    op.drop_index(op.f('ix_customagentdefinition_custom_agent_id'), table_name='customagentdefinition')
    op.drop_index(op.f('ix_customagentdefinition_created_at'), table_name='customagentdefinition')
    op.drop_table('customagentdefinition')
    op.drop_index(op.f('ix_agentteam_tenant_id'), table_name='agentteam')
    op.drop_index(op.f('ix_agentteam_is_active'), table_name='agentteam')
    op.drop_index(op.f('ix_agentteam_created_at'), table_name='agentteam')
    op.drop_index(op.f('ix_agentteam_agent_team_id'), table_name='agentteam')
    op.drop_table('agentteam')
    # ### end Alembic commands ###
