"""add_project_description_and_conversation_title_fields

Revision ID: 9025eb395671
Revises: b73b3be5cc1d
Create Date: 2025-08-22 18:50:33.269002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9025eb395671'
down_revision: Union[str, Sequence[str], None] = 'b73b3be5cc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Both 'description' column in 'project' table and 'title' column in 'conversation' table
    # already exist in the database schema. This migration is a no-op to acknowledge that the
    # model definitions and database schema are now aligned.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a no-op migration for downgrade as well since we're not actually
    # changing the database schema.
    pass
    # ### end Alembic commands ###
