"""Add file_size, mime_type, status, error_message to ProjectKBFile and extend ToneProfile

Revision ID: abc123def456
Revises: f8c9d7d2a4e1
Create Date: 2025-08-23 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'f8c9d7d2a4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to ProjectKBFile
    op.add_column('projectkbfile', sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('projectkbfile', sa.Column('mime_type', sa.String(), nullable=False, server_default='application/octet-stream'))
    op.add_column('projectkbfile', sa.Column('status', sa.String(), nullable=False, server_default='processing'))
    op.add_column('projectkbfile', sa.Column('error_message', sa.String(), nullable=True))
    
    # Add new columns to ToneProfile
    op.add_column('toneprofile', sa.Column('description', sa.String(), nullable=True))
    op.add_column('toneprofile', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('toneprofile', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    
    # Add indexes
    op.create_index('ix_projectkbfile_tenant_id', 'projectkbfile', ['tenant_id'], unique=False)
    op.create_index('ix_projectkbfile_project_id', 'projectkbfile', ['project_id'], unique=False)
    op.create_index('ix_projectkbfile_status', 'projectkbfile', ['status'], unique=False)
    op.create_index('ix_toneprofile_tenant_id', 'toneprofile', ['tenant_id'], unique=False)
    op.create_index('ix_toneprofile_user_id', 'toneprofile', ['user_id'], unique=False)
    op.create_index('ix_toneprofile_is_default', 'toneprofile', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_toneprofile_is_default', table_name='toneprofile')
    op.drop_index('ix_toneprofile_user_id', table_name='toneprofile')
    op.drop_index('ix_toneprofile_tenant_id', table_name='toneprofile')
    op.drop_index('ix_projectkbfile_status', table_name='projectkbfile')
    op.drop_index('ix_projectkbfile_project_id', table_name='projectkbfile')
    op.drop_index('ix_projectkbfile_tenant_id', table_name='projectkbfile')
    
    # Drop columns from ToneProfile
    op.drop_column('toneprofile', 'updated_at')
    op.drop_column('toneprofile', 'is_default')
    op.drop_column('toneprofile', 'description')
    
    # Drop columns from ProjectKBFile
    op.drop_column('projectkbfile', 'error_message')
    op.drop_column('projectkbfile', 'status')
    op.drop_column('projectkbfile', 'mime_type')
    op.drop_column('projectkbfile', 'file_size')
    # ### end Alembic commands ###