"""add default_retention_policy_days to tenant

Revision ID: dc8b9721e09c
Revises: c172fb851fc2
Create Date: 2025-10-12 20:21:06.460351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc8b9721e09c'
down_revision: Union[str, Sequence[str], None] = 'c172fb851fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agentteam', schema=None) as batch_op:
        batch_op.alter_column('is_system_agent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_agentteam_tenant_active'))
        batch_op.drop_index(batch_op.f('ix_agentteam_version'))

    with op.batch_alter_table('customagentdefinition', schema=None) as batch_op:
        batch_op.alter_column('is_system_agent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_customagentdefinition_tenant_active'))
        batch_op.drop_index(batch_op.f('ix_customagentdefinition_version'))

    with op.batch_alter_table('executioncost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executioncost_job_id'), ['job_id'], unique=False)

    with op.batch_alter_table('executiontracestep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executiontracestep_tenant_job'))
        batch_op.drop_index(batch_op.f('ix_executiontracestep_tenant_timestamp'))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_output_data_uri'))
        batch_op.drop_index(batch_op.f('ix_job_tenant_created'))
        batch_op.drop_index(batch_op.f('ix_job_tenant_status'))
        batch_op.drop_index(batch_op.f('ix_job_trace_data_uri'))
        batch_op.drop_column('output_data_uri')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    with op.batch_alter_table('projectkbfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_policy_days', sa.Integer(), nullable=False, server_default='365'))
        batch_op.add_column(sa.Column('archive_after', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_projectkbfile_status'))
        batch_op.create_index(batch_op.f('ix_projectkbfile_archive_after'), ['archive_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectkbfile_retention_policy_days'), ['retention_policy_days'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_retention_policy_days', sa.Integer(), nullable=False, server_default='365'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_tenant_default_retention_policy_days'), ['default_retention_policy_days'], unique=False)

    with op.batch_alter_table('toneprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toneprofile_is_default'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('userobservation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userobservation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('toneprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toneprofile_is_default'), ['is_default'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_default_retention_policy_days'))
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('default_retention_policy_days')

    with op.batch_alter_table('projectkbfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectkbfile_retention_policy_days'))
        batch_op.drop_index(batch_op.f('ix_projectkbfile_archive_after'))
        batch_op.create_index(batch_op.f('ix_projectkbfile_status'), ['status'], unique=False)
        batch_op.drop_column('archive_after')
        batch_op.drop_column('retention_policy_days')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_data_uri', sa.VARCHAR(length=2048), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_trace_data_uri'), ['trace_data_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tenant_status'), ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_tenant_created'), ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_output_data_uri'), ['output_data_uri'], unique=False)

    with op.batch_alter_table('executiontracestep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executiontracestep_tenant_timestamp'), ['tenant_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_executiontracestep_tenant_job'), ['tenant_id', 'job_id'], unique=False)

    with op.batch_alter_table('executioncost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executioncost_job_id'))

    with op.batch_alter_table('customagentdefinition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customagentdefinition_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('ix_customagentdefinition_tenant_active'), ['tenant_id', 'is_active'], unique=False)
        batch_op.alter_column('is_system_agent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('agentteam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentteam_version'), ['version'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentteam_tenant_active'), ['tenant_id', 'is_active'], unique=False)
        batch_op.alter_column('is_system_agent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
