"""add_tenant_model_and_tenant_id_fields

Revision ID: e8e79e727330
Revises: 8747b1bc101a
Create Date: 2025-08-21 16:35:23.143814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e79e727330'
down_revision: Union[str, Sequence[str], None] = '8747b1bc101a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Tenant table
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subdomain'), 'tenant', ['subdomain'], unique=True)
    op.create_index(op.f('ix_tenant_tenant_id'), 'tenant', ['tenant_id'], unique=True)
    
    # Add tenant_id columns as nullable first
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('projectkbfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('toneprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_user_email'), ['email'], unique=False)
    
    # Create foreign key constraints (SQLite will ignore these in batch mode)
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_conversation_tenant_id', 'tenant', ['tenant_id'], ['id'])
    
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_message_tenant_id', 'tenant', ['tenant_id'], ['id'])
    
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_project_tenant_id', 'tenant', ['tenant_id'], ['id'])
    
    with op.batch_alter_table('projectkbfile', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_projectkbfile_tenant_id', 'tenant', ['tenant_id'], ['id'])
    
    with op.batch_alter_table('toneprofile', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_toneprofile_tenant_id', 'tenant', ['tenant_id'], ['id'])
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_tenant_id', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_tenant_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_user_email'))
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('last_login')
        batch_op.drop_column('provider')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('name')
        batch_op.drop_column('email')
    
    with op.batch_alter_table('toneprofile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_toneprofile_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    
    with op.batch_alter_table('projectkbfile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projectkbfile_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    
    op.drop_index(op.f('ix_tenant_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_subdomain'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
