"""Add ScheduledTask table

Revision ID: f8c9d7d2a4e1
Revises: e7170db9163a
Create Date: 2025-08-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f8c9d7d2a4e1'
down_revision = 'e7170db9163a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('goal_input', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_log', sa.String(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('last_execution_result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add indexes for efficient querying
    op.create_index('ix_scheduledtask_tenant_id', 'scheduledtask', ['tenant_id'], unique=False)
    op.create_index('ix_scheduledtask_status', 'scheduledtask', ['status'], unique=False)
    op.create_index('ix_scheduledtask_scheduled_at', 'scheduledtask', ['scheduled_at'], unique=False)
    op.create_index('ix_scheduledtask_tenant_status_scheduled', 'scheduledtask', ['tenant_id', 'status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduledtask_tenant_status_scheduled', table_name='scheduledtask')
    op.drop_index('ix_scheduledtask_scheduled_at', table_name='scheduledtask')
    op.drop_index('ix_scheduledtask_status', table_name='scheduledtask')
    op.drop_index('ix_scheduledtask_tenant_id', table_name='scheduledtask')
    op.drop_table('scheduledtask')
    # ### end Alembic commands ###